# Use the latest 2.1 version of CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1
jobs:
  build:
    environment:
      VERSION: &version 0.0.1
      # use go modules
      GO111MODULE: "on"
    docker:
      - image: &go_image mschurenko/golang:1.12.4-alpine-git
    working_directory: /go/src/github.com/mschurenko/docker-cloner
    steps:
      - checkout
      - run: mkdir ./workspace
      - run: GOOS=linux go build -ldflags "-X main.version=$VERSION" -o workspace/docker-cloner
      - persist_to_workspace:
          root: workspace
          paths:
            - docker-cloner
  test:
    docker:
      - image: docker:18.09.1-git
    steps:
      - setup_remote_docker
      - attach_workspace:
          at: ./artifacts
      - run: apk add --no-cache jq
      - run: docker run --rm -d --name test alpine sleep 120
      - run: >
          c_id=$(./artifacts/docker-cloner
          -memory 200
          -id test
          -cmd "echo In copy contianer. PASSED") &&
          if [[ $(docker inspect $c_id|jq -r '.[0].HostConfig.Memory') -ne $(( 200 * 1024 * 1024 )) ]];then
            echo "Memory limit mismatch"
            exit 1
          fi && docker start -ia $c_id

  publish-github-release:
    environment:
      VERSION: *version
    docker:
      - image: *go_image
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "publish github release"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -n ${VERSION} -soft ${VERSION} ./artifacts/

workflows:
  main:
    jobs:
      - build
      - test:
          requires:
            - build
      - publish-github-release:
          filters:
            branches:
              only: master
          requires:
            - test
